### ISSUE TITLE
Adaptation through fine-tuning with error RuntimeError: Could not infer dtype of numpy.int16

### ISSUE THREAD

**Issue by Dtdavidgit** [AIM-Harvard/foundation-cancer-image-biomarker#309]
## Checklist

- [x ] I've searched the project's [`issues`](https://github.com/foundation_image_biomarker/foundation-image-biomarker/issues?q=is%3Aissue).

## ❓ Question

Hi there, I was trying to finetune the pre-trained model with LUNA16 datasets, I've went through the website and the configuration yaml file, and modify the config based on the suggestion here [fmcib_finetune.yaml](https://github.com/AIM-Harvard/foundation-cancer-image-biomarker/blob/master/experiments/adaptation/fmcib_finetune.yaml)

However, the process stopped due to an error

```
192 M     Trainable params
0         Non-trainable params
192 M     Total params
771.482   Total estimated model params size (MB)
168       Modules in train mode
0         Modules in eval mode
Sanity Checking: |                                                                            | 0/? [00:00<?, ?it/s][rank3]: Traceback (most recent call last):
[rank3]:   File "/home/user/.conda/envs/fmcib/bin/lighter", line 8, in <module>
[rank3]:     sys.exit(interface())
[rank3]:   File "/home/user/.conda/envs/fmcib/lib/python3.9/site-packages/lighter/utils/cli.py", line 23, in interface
[rank3]:     fire.Fire(commands)
[rank3]:   File "/home/user/.conda/envs/fmcib/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
[rank3]:     component_trace = _Fire(component, args, parsed_flag_args, context, name)
[rank3]:   File "/home/user/.conda/envs/fmcib/lib/python3.9/site-packages/fire/core.py", line 566, in _Fire
[rank3]:     component, remaining_args = _CallAndUpdateTrace(
[rank3]:   File "/home/user/.conda/envs/fmcib/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
[rank3]:     component = fn(*varargs, **kwargs)
[rank3]:   File "/home/user/.conda/envs/fmcib/lib/python3.9/site-packages/lighter/utils/runner.py", line 70, in run_trainer_method
[rank3]:     getattr(trainer, method)(system)
[rank3]:   File "/home/user/.conda/envs/fmcib/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 538, in fit
[rank3]:     call._call_and_handle_interrupt(
[rank3]:   File "/home/user/.conda/envs/fmcib/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 46, in _call_and_handle_interrupt
[rank3]:     return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
[rank3]:   File "/home/user/.conda/envs/fmcib/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 105, in launch
[rank3]:     return function(*args, **kwargs)
[rank3]:   File "/home/user/.conda/envs/fmcib/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 574, in _fit_impl
[rank3]:     self._run(model, ckpt_path=ckpt_path)
[rank3]:   File "/home/user/.conda/envs/fmcib/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 981, in _run
[rank3]:     results = self._run_stage()
[rank3]:   File "/home/user/.conda/envs/fmcib/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1023, in _run_stage
[rank3]:     self._run_sanity_check()
[rank3]:   File "/home/user/.conda/envs/fmcib/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1052, in _run_sanity_check
[rank3]:     val_loop.run()
[rank3]:   File "/home/user/.conda/envs/fmcib/lib/python3.9/site-packages/pytorch_lightning/loops/utilities.py", line 178, in _decorator
[rank3]:     return loop_run(self, *args, **kwargs)
[rank3]:   File "/home/user/.conda/envs/fmcib/lib/python3.9/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 128, in run
[rank3]:     batch, batch_idx, dataloader_idx = next(data_fetcher)
[rank3]:   File "/home/user/.conda/envs/fmcib/lib/python3.9/site-packages/pytorch_lightning/loops/fetchers.py", line 133, in __next__
[rank3]:     batch = super().__next__()
[rank3]:   File "/home/user/.conda/envs/fmcib/lib/python3.9/site-packages/pytorch_lightning/loops/fetchers.py", line 60, in __next__
[rank3]:     batch = next(self.iterator)
[rank3]:   File "/home/user/.conda/envs/fmcib/lib/python3.9/site-packages/pytorch_lightning/utilities/combined_loader.py", line 341, in __next__
[rank3]:     out = next(self._iterator)
[rank3]:   File "/home/user/.conda/envs/fmcib/lib/python3.9/site-packages/pytorch_lightning/utilities/combined_loader.py", line 142, in __next__
[rank3]:     out = next(self.iterators[0])
[rank3]:   File "/home/user/.conda/envs/fmcib/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
[rank3]:     data = self._next_data()
[rank3]:   File "/home/user/.conda/envs/fmcib/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1465, in _next_data
[rank3]:     return self._process_data(data)
[rank3]:   File "/home/user/.conda/envs/fmcib/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1491, in _process_data
[rank3]:     data.reraise()
[rank3]:   File "/home/user/.conda/envs/fmcib/lib/python3.9/site-packages/torch/_utils.py", line 715, in reraise
[rank3]:     raise exception
[rank3]: RuntimeError: Caught RuntimeError in DataLoader worker process 0.
[rank3]: Original Traceback (most recent call last):
[rank3]:   File "/home/user/.conda/envs/fmcib/lib/python3.9/site-packages/monai/transforms/transform.py", line 141, in apply_transform
[rank3]:     return _apply_transform(transform, data, unpack_items, lazy, overrides, log_stats)
[rank3]:   File "/home/user/.conda/envs/fmcib/lib/python3.9/site-packages/monai/transforms/transform.py", line 98, in _apply_transform
[rank3]:     return transform(data, lazy=lazy) if isinstance(transform, LazyTrait) else transform(data)
[rank3]:   File "/home/user/.conda/envs/fmcib/lib/python3.9/site-packages/monai/transforms/intensity/array.py", line 902, in __call__
[rank3]:     img = convert_to_tensor(img, track_meta=get_track_meta())
[rank3]:   File "/home/user/.conda/envs/fmcib/lib/python3.9/site-packages/monai/utils/type_conversion.py", line 169, in convert_to_tensor
[rank3]:     return _convert_tensor(data, dtype=dtype, device=device)
[rank3]:   File "/home/user/.conda/envs/fmcib/lib/python3.9/site-packages/monai/utils/type_conversion.py", line 149, in _convert_tensor
[rank3]:     tensor = torch.as_tensor(tensor, **kwargs)
[rank3]: RuntimeError: Could not infer dtype of numpy.int16

```

I believe the error comes from here [rank3]: RuntimeError: Could not infer dtype of numpy.int16

If possible, can you please guide me how to run this through, thank you.

**Comment by amabilee** [comment]
This error often occurs when there's a mismatch between the **expected** data type and the **actual** data type being processed.

Have you tried checking the data types?
You can use `numpy.dtype` to check the data type of your arrays.

**Comment by surajpaib** [comment]
Hi @Dtdavidgit 

This seems like it might be due to numpy versioning. The previous build of this package does not lock versions but I'm considering doing that in the next release. 

Do you mind sharing versions of the packages you have installed?

**Comment by Dtdavidgit** [comment]
Hi @surajpaib 

I am using numpy 1.26.4

```
Name: numpy
Version: 1.26.4
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: Copyright (c) 2005-2023, NumPy Developers.
```

**Comment by surajpaib** [comment]
@Dtdavidgit 
Thanks!

Ok, now I think the issue might be something entirely different. Could you try moving the line https://github.com/AIM-Harvard/foundation-cancer-image-biomarker/blob/b45a4988fa051112abf6e0ceddc4ab1797409ab9/experiments/adaptation/fmcib_finetune.yaml#L92

to the top of the transforms, before the `NormalizeIntensity` transform and report if that fixes it?

**Comment by Dtdavidgit** [comment]
> @Dtdavidgit Thanks!
> 
> Ok, now I think the issue might be something entirely different. Could you try moving the line
> 
> https://github.com/AIM-Harvard/foundation-cancer-image-biomarker/blob/b45a4988fa051112abf6e0ceddc4ab1797409ab9/experiments/adaptation/fmcib_finetune.yaml#L92
> 
> to the top of the transforms, before the `NormalizeIntensity` transform and report if that fixes it? You would need to do this for both train and val

@surajpaib Thank you for your assistance, however, after I modified the config file, it still shows the same error.

Please refer the whole config file as following,

```
trainer:
  _target_: pytorch_lightning.Trainer
  benchmark: True
  max_epochs: 100
  check_val_every_n_epoch: 5
  accelerator: gpu
  devices: 4
  # sync_batchnorm: True
  # precision: 16
  log_every_n_steps: 1
  logger:
    _target_: pytorch_lightning.loggers.WandbLogger
    name: "fmcib_finetune"
    project: "fmcib"
    save_dir: "./logs"

  callbacks:
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      dirpath:  ./finetune # Note: Change as appropriate
      verbose: True
      save_last: True
      every_n_epochs: 1
      save_on_train_epoch_end: True

system:
    _target_: lighter.LighterSystem
    batch_size: 16
    pin_memory: True
    drop_last_batch: False 
    num_workers: 12
    model:
        _target_: fmcib.models.LoadModel
        trunk:
          _target_: monai.networks.nets.resnet50
          widen_factor: 2
          n_input_channels: 1
          feed_forward: False
        weights_path: "./model_weights.torch" # Note: Path to the FM weights. Download from Zenodo or HF
        heads: [4096, 2048, 1] # Note: Change to [4096, 2048, 1] for Task 2 and [4096, 2048, 512, 256, 1] Task 3


    postprocessing:
      metrics:
        pred:
          - "$lambda x: torch.sigmoid(x)" # Note: Change to $lambda x: torch.sigmoid(x) for Task 2 and Task 3    
      criterion:
        target: # Note: Uncomment for Task 2 and Task 3
          - "$lambda x: x.float()" 

    criterion:
        _target_: torch.nn.BCEWithLogitsLoss # Note: Change to torch.nn.BCEWithLogitsLoss for Task 2 and Task 3

    optimizer:
        _target_: torch.optim.Adam
        params: "$@system#model.parameters()"
        # lr: "$((@system#batch_size * @trainer#devices)/256) * 0.1" # Compute LR dynamically for different batch sizes
        # weight_decay: 0.0
        # momentum: 0.9

    scheduler:
      _target_: torch.optim.lr_scheduler.StepLR
      optimizer: "@system#optimizer"
      step_size: 30

    metrics:
      train: 
        - _target_: torchmetrics.AveragePrecision
          task: 'binary' # Note: Change to `binary` for Task 2 and Task 3 and remove num_classes below
          num_classes: 8 
        - _target_: torchmetrics.AUROC
          task: 'binary' # Note: Change to `binary` for Task 2 and Task 3 and remove num_classes below
          num_classes: 8

      val: "%#train"
      test: "%#train"

    datasets:
      train:
        _target_: fmcib.datasets.SSLRadiomicsDataset
        path: "/mnt/data/david/foundation-cancer-image-biomarker/data/preprocessing/luna16/annotations/task2_train.csv" # Note: Change path
        label: "malignancy" # Note: Change to "malignancy" for Task 2 and "survival" for Task 3
        radius: 25
        orient: False # Note: Set orient to False for task 2 and task 3
        resample_spacing: [1, 1, 1]
        enable_negatives: False
        transform:
            _target_: monai.transforms.Compose
            transforms:
                - _target_: monai.transforms.ToTensor
                - _target_: monai.transforms.NormalizeIntensity
                  subtrahend: -1024
                  divisor: 3072            
                - _target_: monai.transforms.EnsureChannelFirst
                  channel_dim: no_channel
                - _target_: monai.transforms.SpatialPad
                  spatial_size: [50, 50, 50]
                - _target_: monai.transforms.RandGaussianSmooth
                  prob: 0.5
                - _target_: monai.transforms.RandAffine
                  prob: 0.5
                  translate_range: [10, 10, 10]
                - _target_: monai.transforms.RandAxisFlip
                  prob: 0.5
                - _target_: monai.transforms.RandRotate90
                  prob: 0.5

      val:
        _target_: fmcib.datasets.SSLRadiomicsDataset
        path: "/mnt/data/david/foundation-cancer-image-biomarker/data/preprocessing/luna16/annotations/task2_val.csv" # Note: Change path
        label: "@system#datasets#train#label"
        radius: "@system#datasets#train#radius"
        orient: "@system#datasets#train#orient"
        resample_spacing: "@system#datasets#train#resample_spacing"
        enable_negatives: "@system#datasets#train#enable_negatives"
        transform:
            _target_: monai.transforms.Compose
            transforms:
                - _target_: monai.transforms.ToTensor
                - _target_: monai.transforms.NormalizeIntensity
                  subtrahend: -1024
                  divisor: 3072            
                - _target_: monai.transforms.EnsureChannelFirst
                  channel_dim: no_channel
                - _target_: monai.transforms.SpatialPad
                  spatial_size: [50, 50, 50]

                  
      test: null
```
