### ISSUE TITLE
ValueError in FineTuning

### ISSUE THREAD

**Issue by yanniangu** [AIM-Harvard/foundation-cancer-image-biomarker#311]
Thank you for providing the open-source code—it's been incredibly helpful and valuable in my work. I truly appreciate the effort put into making this resource available to the community.

But when following the [Pre-training the FM](https://aim-harvard.github.io/foundation-cancer-image-biomarker/replication-guide/reproduce_fm/) guide for LUNA16 on Task 2, I encountered the following error:
```
raise ValueError(f"Target size ({target.size()}) must be the same as input size ({input.size()})")
ValueError: Target size (torch.Size([32])) must be the same as input size (torch.Size([32, 1]))
```

I believe this issue is caused by a mismatch in target and input dimensions in the configuration:
```
    postprocessing:
      metrics:
        pred:
          - "$lambda x: torch.sigmoid(x)" # Note: Change to $lambda x: torch.sigmoid(x) for Task 2 and Task 3    
      criterion:
        target: # Note: Uncomment for Task 2 and Task 3
          - "$lambda x: x.float()"

    criterion:
        _target_: torch.nn.BCEWithLogitsLoss # Note: Change to torch.nn.BCEWithLogitsLoss for Task 2 and Task 3
```

Any insights on how to resolve this mismatch would be appreciated.

**Comment by yanniangu** [comment]
```
postprocessing:
      metrics:
        pred:
          - "$lambda x: torch.sigmoid(x)" # Note: Change to $lambda x: torch.sigmoid(x) for Task 2 and Task 3    
      criterion:
        pred:
          - "$lambda x: x.flatten().float()"  # Prediction has an unnecessary dimension ([N, 1]), flattening it
        target: # Note: Uncomment for Task 2 and Task 3
          - "$lambda x: x.float()"
```

but...
```
ValueError: Expected argument `target` to be an int or long tensor with ground truth labels but got tensor with dtype torch.float32
```

**Comment by surajpaib** [comment]
Hi @yanniangu 

Seems to have been some error in the pipeline - not sure if a package update caused it or so.

Editing the postprocessing to below should make it work. 

```yaml
    postprocessing:
      metrics:
        pred:
          - "$lambda x: torch.sigmoid(x)" # Note: Change to $lambda x: torch.sigmoid(x) for Task 2 and Task 3
        target:  # Note: Uncomment for Task 2 and Task 3
          - "$lambda x: x.long()"
      criterion: # Note: Uncomment for Task 2 and Task 3
        pred:
          - "$lambda x: x.squeeze(1)"
        target: 
          - "$lambda x: x.float()"
```
