### ISSUE TITLE
WARNING: unexpected keys   -  Can I directly load my fine-tuned checkpoints?

### ISSUE THREAD

**Issue by hhaentze** [AIM-Harvard/foundation-cancer-image-biomarker#320]
## Checklist

- [x] I've searched the project's [`issues`](https://github.com/foundation_image_biomarker/foundation-image-biomarker/issues?q=is%3Aissue).

## ❓ Question
I fine-tuned the model to work as a binary classifier for malignancy. Afterwards I used it for inference. It works (in the sense that it predicts a singular value for each item) but I get a large warning regarding unexpected keys:

```bash
2025-03-04 13:51:37.984 | WARNING  | fmcib.models.load_model:load:117 - Missing keys: [] and unexpected keys: 
['model.trunk.conv1.weight', 'model.trunk.bn1.weight', 'model.trunk.bn1.bias', 'model.trunk.bn1.running_mean', 
'model.trunk.bn1.running_var', 'model.trunk.bn1.num_batches_tracked', 'model.trunk.layer1.0.conv1.weight',
 'model.trunk.layer1.0.bn1.weight', 'model.trunk.layer1.0.bn1.bias 
...
layer4.2.bn3.running_var', 'model.trunk.layer4.2.bn3.num_batches_tracked']
2025-03-04 13:51:37.984 | INFO     | fmcib.models.load_model:load:129 - Loaded pretrained model weights 
```

It looks to me as if the checkpoint I am specifying has not saved all the weights. I'm not sure if this is a bug or if I simply specified the wrong weights file. Why is there a warning message and was it correct to specify only the checkpoint?

## 📎 Additional context
finetune.yaml:
```yaml
trainer:
  _target_: pytorch_lightning.Trainer
  benchmark: True
  max_epochs: 100
  check_val_every_n_epoch: 5
  accelerator: gpu
  devices: 1
  ...
  callbacks:
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      dirpath:  ./finetuning 
      verbose: True
      save_last: True
      every_n_epochs: 1
      save_on_train_epoch_end: True
...
system:
    _target_: lighter.LighterSystem
    batch_size: 32
    pin_memory: True
    drop_last_batch: False 
    num_workers: 12
    model:
        _target_: fmcib.models.LoadModel
        trunk:
          _target_: monai.networks.nets.resnet50
          widen_factor: 2
          n_input_channels: 1
          feed_forward: False
        weights_path: "./model_weights.torch" # Downloaded from Zenodo
        heads: [4096, 2048, 1] 

    postprocessing:
      metrics:
        pred:
          # - "$lambda x: torch.softmax(x, 1)"
          - "$lambda x: torch.sigmoid(x)" 
        target: 
          - "$lambda x: x.long()"
      criterion:
        pred:
          - "$lambda x: x.squeeze(1)"
        target: 
          - "$lambda x: x.float()"
```

predict.yaml:
```yaml
trainer:
    _target_: pytorch_lightning.Trainer
    benchmark: True
    max_epochs: 100
    check_val_every_n_epoch: 4
    accelerator: gpu
    devices: 1
    log_every_n_steps: 50
    logger: False
    callbacks:
        - _target_: fmcib.callbacks.SavePredictions
          path: "preds.csv" 
          save_preview_samples: 1

system:
    _target_: lighter.LighterSystem
    batch_size: 32
    pin_memory: True
    num_workers: 8
    model:
        _target_: fmcib.models.LoadModel
        trunk:
            _target_: monai.networks.nets.resnet50
            widen_factor: 2
            n_input_channels: 1
            feed_forward: False
        weights_path: "./finetuning/last.ckpt" # Here I specified the last checkpoint
        heads: [4096, 2048, 1] 

    postprocessing:
      logging:
        pred:
          - "$lambda x: torch.sigmoid(x)"
      criterion:
        target: 
          - "$lambda x: x.float()"

    criterion: null
```
